---
- name: "Administra httpd"
  hosts: all
  become: yes
  gather_facts: no
  vars:
    httpd_service_state: restarted
  tasks:
    - name: "Estado servicio"
      service:
        name: "httpd"
        state: "{{ httpd_service_state }}"
...
