---
- name: httpd bonus 1
  hosts: all
  vars:
    virtualhost_ports:
      - 80
      - 81
  become: yes
  tasks:
    - name: Crea directorios
      file:
        path: /var/www/html/service-{{ item }}
        state: directory
      loop: "{{ virtualhost_ports }}"

    - name: Sustituir httpd.con
      template: 
        src: httpd.conf.j2
        dest: /etc/httpd/conf.d/defaults.conf
        mode: 0664
      notify: restart_httpd
      
    - name: Comentar linea del puerto 80
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80 '
        line: #Listen 80
        state: present
        
  handlers:
    - name: restart_httpd
      service: 
        name: httpd
        state: restarted   
...
