---
- name: bonus 2
  hosts: all
  become: yes
  tasks:
    - name: obtener puertos httpd abiertos
      shell:
        cmd: netstat -putan | grep -i listen | grep [htt]pd|awk '{print $4}' | cut -d ":" -f 4
      register: puertos
    # - name: generar facts.d
    #   blockinfile:
    #     path: /etc/ansible/facts.d/port.fact
    #     block: |
    #       [{{item }}]
    #       {{ item }}
    #   loop: "{{ puertos.stdout_lines }}"
          
    - name: crear fichero index.html
      template:
        src: index.html.j2
        dest: /var/www/html/service-{{ puerto }}/index.html
      loop: "{{ puertos.stdout_lines }}"
      loop_control:
        loop_var: puerto
...