---
- name: Creacion de usuarios
  hosts: all
  vars:
    users: 
      - user01
    file: user_created_date.txt
  become: yes
  tasks:
  - name: "Creando Usuario {{ users }}"
    user:
      name: "{{ users }}"
      comment: "Usuario {{ users }}"
      create_home: yes
  
  - name: "Creando fichero con fecha de creacion"
    shell: date > /home/{{ users }}/{{ file }}
  
  - name: Cambiando permios fichero /home/users/
    file: 
      path: /home/{{ users }}/{{ file }}
      owner: "{{ users }}"
      group: "{{ users }}"
      mode: 0644   
...
