---
- name: Creacion de usuarios
  hosts: all
  vars:
    users: 
      - user01
    file: user_created_date.txt
  become: yes
  tasks:
  - name: "Creando Usuario {{ users }}"
    user:
      name: "{{ item }}"
      comment: "Usuario {{ item }}"
      create_home: yes
    loop: "{{ users }}"
  
  - name: "Creando fichero con fecha de creacion"
    shell: date > /home/{{ item }}/{{ file }}
    loop: "{{ users }}"
  
  - name: Cambiando permios fichero /home/users/
    file: 
      path: /home/{{ item }}/{{ file }}
      owner: "{{ item }}"
      group: "{{ item }}"
      mode: 0644  
    loop: "{{ users }}"
...
