---
- name: "Administra mariadb"
  hosts: all
  become: yes
  grather_facts: no
  vars:
    mysql_service_state: restarted
  tasks:
    - name: "Estado servicio"
      service:
        name: "mariadb"
        state: "{{ mysql_service_state }}"
...