- hosts: localhost
  gather_facts: false
  
  collections:
    - community.kubernetes
    
  tasks:
    - name: Asegurar que awx-ns exists
      k8s:
        api_version: v1
        kind: Namespace
        name: awx-ns
        state: present
