- hosts: localhost
  gather_facts: false
  
  collections:
    - community.kubernetes
    
  tasks:
    - k8s: Asegurar que awx-ns exists
        api_version: v1
        kind: Namespace
        name: awx-ns
        state: present
